let lab = ["AB0- og RhD-blodtypebestemmelse rutine, KIA	",
    "Acetylcholinreceptor-Ab(IgG) (SSI 446), KBA	",
    "Actin-IgG;P, KBA	",
    "Actinomyces, KMD	",
    "Adalimumab;P, KBA	",
    "Adalimumab-Ab;P, KBA	",
    "ADAMTS13 protein:P, KBA	",
    "Adenosindeaminase;Pl, KBA	",
    "Adenovirus (DNA);P (SSI254), KBA	",
    "Adenovirus i fæces, KMD	",
    "Adrenalin;Pt(U), KBA	",
    "Adrenalin;U, KBA	",
    "Alanintransaminase (ALAT);P, KBA	",
    "Albumin / Kreatinin ratio;U, KBA	",
    "Albumin; P, KBA	",
    "Albumin; Pt (U), KBA	",
    "Albumin; U, KBA	< 20 mg/l",
    "Albumin;Asc, KBA	",
    "Albumin;Csv, KBA	",
    "Albumin;Ldv, KBA	",
    "Albumin;Plv, KBA	",
    "Aldolase;P, KBA	",
    "Aldosteron;P, KBA	",
    "Aldosteron;Pt(U), KBA	",
    "Alfa-1-Føtoprotein;P, KBA	",
    "Alfa-2 Makroglobulin;P, KBA	",
    "Alifatisk carboxylat (C14-C26); Pt(F), KBA	",
    "Allergiudredning Oversigt, SKB	",
    "Allergiudredning på Biokemiske afdelinger i Region Sjælland, SKB	",
    "Aluminium;P, KBA	",
    "Alzheimer: Pakke (SSI 452), KBA	",
    "Amfetamin;U + analog, KBA	",
    "Amikacin;P, KBA	",
    "Aminosyrer;P, KBA	",
    "Amiodaron;P, KBA	",
    "Amisulprid;P, KBA	",
    "Amitriptylin gruppe;P, KBA	",
    "Ammonium; P, KBA	",
    "Amoxicillin-antistof (IgE); P-, KBA	",
    "Ampicilloyl (c5)-IgE;P, KBA	",
    "Amylase pancreastype;P, KBA	",
    "Amylase; Asc., KBA	",
    "Amylase; U, KBA	",
    "Amylase;P, KBA	",
    "Amylase;Plv, KBA	",
    "Amylasetype gruppe;P, KBA	",
    "ANCA(IgG) (semikvant) gruppe;P, KBA	",
    "Androgen gruppe;P, KBA	",
    "Androstendion;P, KBA	",
    "Anion gap(inkl. K+);P, KBA	",
    "Ansvarliste med versioner og bilag, KMD	",
    "Antimüllersk hormon;P, KBA	",
    "Antithrombin (enz.: IIa);P, KBA	",
    "Antithrombin(enzXa);P, KBA	",
    "Antitrypsin;P, KBA	",
    "Apixaban;P, KBA	",
    "Apolipoprotein A1;P, KBA	",
    "Arbejdsark - Følgeseddel til in-house analyser, SKB	",
    "Argipressin [ADH];P, KBA	",
    "Aripiprazol+metabolit gruppe;P, KBA	",
    "Array CGH (Comparativ Genom Hybrid.); DNA(spec.), KBA	",
    "Aspartattransaminase [ASAT];P, KBA	",
    "Aspergillus galactomannan (antigen), KMD	",
    "Aspergillus IgG antistof, KMD	",
    "Atypisk pneumonipakke, PCR, KMD	",
    "Autoimmun encephalitis primær screening-IgG; (SSI 4511), KBA	",
    "Autoimmun encephalitis sekundær screening-IgG; (SSI 4512), KBA	",
    "	",
    "BAC-test, KIA	",
    "Bakterielt/svampe DNA påvisning ved 16S/18S rRNA-genet PCR/sekventering, KMD	",
    "Bartonella-antistof;P, KBA	",
    "Base excess;Ecv, KBA	",
    "Basisk fosfatase;P, KBA	",
    "Basisk fosfatasetype gruppe;BasF(P), KBA	",
    "Basisk Phosphatase, knogletype;massek., KBA	",
    "BCHE-gen;DNA, KBA	",
    "BCR/ABL-translokation,t(9;22), KBA	",
    "BCRABL-Kvantitativ;RNA, KBA	",
    "BCRABL-Påvisning;RNA, KBA	",
    "Benzodiazepiner;U, KBA	",
    "Benzodiazepiner;U - udvidet, KBA	",
    "Bestillingsseddel Klinisk biokemi til praksis 2017, STP	",
    "Bestillingsseddel til depotet Nykøbing F., KMD	",
    "beta-2-Glykoprotein 1-Ab(IgG);P, KBA	",
    "beta-2-Glykoprotein 1-Ab(IgM);P, KBA	",
    "Beta-2-mikroglobulin;P, KBA	",
    "Beta-2-Transferrin, KBA	",
    "BF test, KIA	",
    "Bigift-antistof (IgE); P-, KBA	",
    "Bilirubin Konjugeret;P, KBA	",
    "Bilirubiner;P, KBA	",
    "Bindevævssygdom-relateret-Ab[ANA];P (ANA-screening), KBA	",
    "Binyrebark-Ab(IgG);P, KBA	",
    "Biologiske forprøver HBV,HCV,HIV, KIA	",
    "Biopsier/Vævsprøver til dyrkning, KMD	",
    "Bisacodyl;U, KBA	",
    "Bloddyrkningskolber, KMD	",
    "Blodprøver og ekg - patientinformation, PTI	",
    "Blodprøver, børn - patientinformation, PTI	",
    "Blodprøvetagning til bloddyrkning, KMD	",
    "Blodtype gravid, KIA	",
    "Bly;B, KBA	",
    "Bordetella pertussis og Bordetella parapertussis (kighoste) ved PCR., KMD	",
    "Bordetella pertussis-Ab;P (SSI 667), KBA	",
    "Borrelia antistoffer IgM og IgG i serum, KMD	",
    "Borrelia Burgdorferi -Ab gruppe;P, KBA	",
    "Borrelia IgM og IgG antistoffer i spinalvæske - Intrathekal syntese, KMD	",
    "Brivaracetam;P, KBA	",
    "Bromid;P, KBA	",
    "Bronkoalveolær lavage (BAL) - Bronkialskyllevæske, KMD	",
    "Brucella-Ab;P (SSI 304), KBA	",
    "Buffycoat, KIA	",
    "	",
    "Cadmium;B, KBA	",
    "Calcitonin;P, KBA	",
    "Calcium (albuminkorrigeret);P, KBA	",
    "Calcium (II); stofhast. Pt(U), KBA	",
    "Calcium / Kreatinin;U, KBA	",
    "Calcium/Kreat.clearance ratio;Nyre, KBA	",
    "Calcium;P, KBA	",
    "Calcium-ion frit, KBA	",
    "Calcium-ion frit (pH 7,40);P, KBA	",
    "Calciumkanal P/Q-type-Ab(IgG);P (SSI 712), KBA	",
    "Calprotectin i afføring - patientinformation, PTI	",
    "Calprotectin;F, KBA	",
    "Calreticulin-Påvisning;DNA, KBA	",
    "Campylobacter-Ab(IgG,IgM,IgA);P (SSI 367), KBA	",
    "Cancer-antigen 125;P, KBA	",
    "Cancer-antigen 15-3;P, KBA	",
    "Cancer-antigen 19-9;P, KBA	",
    "Candida mannan Antigen og antistof;P (SSI 044), KBA	",
    "Cannabinoid + Cannabis/creatininiumRatio;U, KBA	",
    "Caput Femoris, hel, KIA	",
    "Carbamazepin;P, KBA	",
    "Carbonmonoxidhæmoglobin;Hb(B), KBA	",
    "Carcinoembryonalt antigen;P, KBA	",
    "Cardiolipin-Ab gruppe;P, KBA	",
    "CASR-gen;DNA, KBA	",
    "CCP (Cykl.citrul.peptid)-Ab (IgG);P, KBA	",
    "CD163;P, KBA	",
    "CD34 hæmatopoietiske stamceller, KIA	",
    "CD34 prognose, KIA	",
    "Cerebrospinalvæske (csv), lumbalpunktur, KBA	",
    "Certolizumab pegol;P , KBA	",
    "Certolizumab pegol-Ab (IgG);P , KBA	",
    "Cervixpodning, KMD	",
    "CFTR-gen;DNA, KBA	",
    "Chikungunya-virus(RNA);P, KBA	",
    "Chikungunya-virus-Ab gruppe;P (R-2021), KBA	",
    "Chitinase;P, KBA	",
    "Chlamydia trachomatis, KMD	",
    "Chlamydophila pneumoniae - antistoffer, KMD	",
    "Chlamydophila pneumoniae PCR, KMD	",
    "Chlamydophila Psitacci, KMD	",
    "Choriogonadotropin [HCG];U, KBA	",
    "Choriogonadotropin beta (HCG);P (doubletest), KBA	",
    "Choriogonadotropin+beta (HCG); P, KBA	",
    "Ciclosporin;B, KBA	",
    "Citalopram;P, KBA	",
    "Citrat;Pt(U), KBA	",
    "CLL-FISH, KBA	",
    "Clobazam og metabolit;P, KBA	",
    "Clobazam;P, KBA	",
    "Clomipramin;P, KBA	",
    "Clonazepam;P, KBA	",
    "Clostridium difficile, påvisning i fæces, KMD	",
    "Clozapin;P, KBA	",
    "CO2;P(vB), KBA	",
    "Cobolt;P, KBA	",
    "Cocain;U, KBA	",
    "Coeliaki-Ab gruppe;P, KBA	",
    "Coeliaki-vævstypeundersøgelse (HLA DQ2 og DQ8), KBA	",
    "Complement C1 est.inhibitor (aktiv);P, KBA	",
    "Complement C1 esteraseinhibitor;P, KBA	",
    "Complement C1q;P, KBA	",
    "Complement C1q-antistof;P, KBA	",
    "Complement C2;P, KBA	",
    "Complement C3c;P, KBA	",
    "Complement C4c;P, KBA	",
    "Complement C5;P, KBA	",
    "Complement splitprodukt C3d;P, KBA	",
    "Complement+immunglobulin;Ercs B, KBA	",
    "Complementaktivitet, klassisk akt.;P, KBA	",
    "Coxiella burnetii-Ab(Q-feber);P (SSI 307), KBA	",
    "CPO – undersøgelse for bærertilstand, KMD	",
    "C-Reaktivt Protein;P, KBA	",
    "CRP-høj sensitiv;P, KBA	",
    "CTx;P(fPt), KBA	",
    "Cylinder;U, KBA	",
    "CYP2C19-gen;B, KBA	",
    "CYP2D6-gen;B, KBA	",
    "Cystatin C;P, KBA	",
    "Cystin;U, KBA	",
    "Cytochrom P450 2D6-Ab(IgG);P, KBA	",
    "Cytologisk undersøgelse - Andet. Patologi, PAT	",
    "Cytologisk undersøgelse - Cervix. Patologi, PAT	",
    "Cytomegalovirus (CMV), DNA, kvantitativ PCR, KMD	",
    "Cytomegalovirus antistoffer, KMD	",
    "	",
    "Dabigatran;P, KBA	",
    "DAN-HEP, KBA	",
    "Dehydroepiandrosteronsulfat;P, KBA	",
    "Denguevirus-PCR/antistof (IgG, IgM) SSI228 ;P, KBA	",
    "Dermatofytter, KMD	",
    "Diabetes autoantistoffer (til Finland);P, KBA	",
    "Diazepam;P, KBA	",
    "Difteri, KMD	",
    "Digoxin;P, KBA	",
    "Direkte Anti-humanglobulin Test (DAT), KIA	",
    "Disopyramid;P, KBA	",
    "DNA (dobbeltstrenget))-Ab(IgG);P, KBA	",
    "DNA til opbevaring, KBA	",
    "DNA topoisomerase 1-Ab(IgG);P, KBA	",
    "DNA-directed RNA polymerase III subunit RPC1-antistof(IgG); P, KBA	",
    "DNA-fragment, trisomi-relateret, KBA	",
    "DNA-Hæmokromatose HFE Mutation, KBA	",
    "Doubletest gruppe; Foster, KBA	",
    "Doxepin;P, KBA	",
    "DPYD-gen;DNA, KBA	",
    "Duloxetin;P, KBA	",
    "	",
    "Echinococcus granulosus(hydatid)-Ab;P (SSI 385), KBA	",
    "eGFR / 1,73m²(CKD-EPI), KBA	",
    "EKG12 (Elektrokardiografi);Pt, KBA	",
    "Ekspektorat, trakealsug og bronkialsekret, KMD	",
    "EMA-bindingsreduktion, arb. enh; Ercs(B), KBA	",
    "Encefalit P/Csv, KBA	",
    "Enterovirus-antistof(IgM); P, KBA	",
    "Eosinofilocyt kationprotein;P, KBA	",
    "Epstein-Barr virus (EBV), DNA, kvantitativ PCR, KMD	",
    "Epstein-Barr virus antistoffer, KMD	",
    "Epstein-Barr virus-antistof;P, KBA	",
    "Erstatnings CPRnr., 2	",
    "Eryth. stamc.(EPO-uafh.)[EEC];B og Marv, KBA	",
    "Erythrocytter;Csv, KBA	",
    "Erythropoietin;P, KBA	",
    "Erytroblaster;B (NRBC), KBA	",
    "Erytrocytantistofidentifikation, KIA	",
    "Erytrocytkomponent, KIA	",
    "Erytrocytkomponent, bestrålet, KIA	",
    "Erytrocytkomponent, vasket, KIA	",
    "Erytrocytkomponent, vasket og bestrålet, KIA	",
    "Erytrocytter (HbF-holdige);Erc(B), KBA	",
    "Erytrocytter, vol.fr.;B, KBA	",
    "Erytrocytter;B, KBA	",
    "Eslicarbazepin;P, KBA	",
    "Estrogen gruppe;P, KBA	",
    "Etanercept;P, KBA	",
    "Etanercept-Ab;P, KBA	",
    "Ethanol;P, KBA	",
    "Ethosuximid;P, KBA	",
    "Everolimus;B, KBA	",
    "	",
    "F2-gen;DNA, KBA	",
    "F5-gen (ARG506GLN);DNA, KBA	",
    "Familiær hyperkolesterolæmi, gruppe;DNA, KBA	",
    "Felbamat;P, KBA	",
    "Ferritin;P, KBA	",
    "Ferroxidase;P, KBA	",
    "Fibrin D-Dimer, Innovance;P, KBA	",
    "Fibrin D-Dimer;P, KBA	",
    "Fibrinogen (koag.);P, KBA	",
    "Film om laboratorieundersøgelser, 4	",
    "Flecainid;P, KBA	",
    "Fluoxetin;P, KBA	",
    "Flupentixol;P, KBA	",
    "Fluphenazin;P, KBA	",
    "Fluvoxamin;P, KBA	",
    "Folat;P, KBA	",
    "Follitropin (FSH), KBA	",
    "Forgiftninger,(ekstra prøver), SKB	",
    "Forsendelse af prøvemateriale Patologi, SP	",
    "Fosfat; P, KBA	",
    "Fosfat;Pt(U)/U, KBA	",
    "Frie lette kæder, KBA	",
    "Fruktosamin;P, KBA	",
    "Frysesnits undersøgelse (peroperativt) - Patologi, PAT	",
    "Fytomenadion;P (Vitamin K), KBA	",
    "	",
    "Gabapentin;P, KBA	",
    "Galdesalte;P, KBA	",
    "gamma-Glutamyltransferase;P, KBA	",
    "Gangliosid antistof, gruppe (SSI 4316), KBA	",
    "Gastrin; P(fPt), KBA	",
    "Genetisk analyse, KBA	",
    "Gentamicin;P, KBA	",
    "Glat muskel-Ab(IgG);P, KBA	",
    "Gliacelleprotein S-100b;P, KBA	",
    "Glomerulær basalmembran-Ab(IgG);P, KBA	",
    "Glucose-6-P-dehydrogenase/Hb;B, KBA	",
    "Glucosebelastning - patientinformation, PTI	",
    "Glukagon, pancreastype;P, KBA	",
    "Glukose belastning (120 min)gruppe;Pt, KBA	",
    "Glukose;Asc., KBA	",
    "Glukose;Csv, KBA	",
    "Glukose;Dialysev (perit), KBA	",
    "Glukose;Ledv, KBA	",
    "Glukose;P, KBA	",
    "Glukose;P(vB; fPt), KBA	",
    "Glukose;Plv., KBA	",
    "Glutamatdecarboxylase(gad65)-Ab;P, KBA	",
    "Golimumab;P, KBA	",
    "Golimumab-Ab;P, KBA	",
    "Gonokokker, KMD	",
    "Gul feber gruppe (SSI 2019), KBA	",
    "	",
    "Haloperidol;P, KBA	",
    "Haptoglobin; P, KBA	",
    "HBOC (BRCA1 + BRCA2) gruppe;DNA, KBA	",
    "HCV LIA, KIA	",
    "Helicobacter Pylori - Antigen i Fæces, KMD	",
    "Helicobacter pylori dyrkning, KMD	",
    "Heparin lav molmasse (enz.);P, KBA	",
    "Heparin-PF4-Ab(IgG)[HIT];P, KBA	",
    "Hepatitis A virus antistof, KMD	",
    "Hepatitis A virus-antistof;P, KBA	",
    "Hepatitis B Virus - Efter vaccination, KIA	",
    "Hepatitis B Virus - Før vaccination, KIA	",
    "Hepatitis B Virus - Kontrol af kendt inficeret, KIA	",
    "Hepatitis B virus (DNA), KIA	",
    "Hepatitis B virus (DNA) genotype;P, KBA	",
    "Hepatitis B virus c-antistof, KIA	",
    "Hepatitis B virus c-antistof(IgM), KIA	",
    "Hepatitis B Virus DNA (kvantitativ), KBA	",
    "Hepatitis B virus e-antigen, KIA	",
    "Hepatitis B virus e-antistof, KIA	",
    "Hepatitis B virus s-antigen, KIA	",
    "Hepatitis B virus s-antigen;P, KBA	",
    "Hepatitis B virus s-antistof, KIA	",
    "Hepatitis B virus s-antistof;P, KBA	",
    "Hepatitis B+C - Udredning, KIA	",
    "Hepatitis C Virus - Kontrol af kendt hepatitis C, KIA	",
    "Hepatitis C virus(RNA), KIA	",
    "Hepatitis C virus(RNA); Taxon(genotype);P, KBA	",
    "Hepatitis C virus(RNA);P (Kvantitativ), KBA	",
    "Hepatitis C virus-Ab;P, KBA	",
    "Hepatitis C virus-antistof, KIA	",
    "Herpes simplex og Varicella Zoster antistof-index (spinalvæske i forhold til serum), KMD	",
    "Herpes Simplexvirus type 1 og 2 IgG antistof, KMD	",
    "Herpesvirus PCR (Herpes Simplex Virus type 1+2 og Varicella Zoster Virus), KMD	",
    "Histidin-tRNA-ligase(Jo-1)-Ab(IgG);P, KBA	",
    "Histologisk undersøgelse - Patologi, PAT	",
    "HIV 1 (DNA);Lkc(B), KBA	",
    "HIV LIA, KIA	",
    "HLA-AB;P, KBA	",
    "HLA-B27(Ag);LKC(B), KBA	",
    "HLA-B-gen (B27);DNA, KIA	",
    "HLA-B-gen;(DNA(spec), KBA	",
    "HLA-DQB1-genDQB1*06:02;DNA, KBA	",
    "HLA-klasse I(Ag) gruppe;Lkc(B), KBA	",
    "HLA-klasse II(Ag) gruppe;Lkc(B), KBA	",
    "Homocystein; P, KBA	",
    "HR Urtikaria;P, KBA	",
    "HR-Test, Inhaleret allerg. HR gruppe;Baso(B), KBA	",
    "HTLV type 1 + 2-antistof;P, KBA	",
    "Hud-antistof;P (SSI 4589), KBA	",
    "Hudsvampe, KMD	",
    "Human imm.defektvirus 1+2-Ab(Ag);P , KBA	",
    "Human immundefekt virus 1(RNA);P (Kvantitativ), KBA	",
    "Human Immundefektvirus (RNA), KIA	",
    "Human immundefektvirus 1(genotype); følsomhed;P, KBA	",
    "Human Immundefektvirus 1+2 (antistof+Ag), KIA	",
    "Hvepsegift-antistof (IgE); P-, KBA	",
    "Hydrogencarbonat (standard);P, KBA	",
    "Hæmatologisk us./problemstilling - Patologi, PAT	",
    "Hæmogl. deriv.gruppe;Csv (Xantochromi), KBA	",
    "Hæmoglobin (frit);P, KBA	",
    "Hæmoglobin A1c gruppe;Hb(B), KBA	",
    "Hæmoglobin;B, KBA	",
    "Hæmoglobin;F, KBA	",
    "Hæmoglobin;Plv spec., KBA	",
    "Hæmoglobinindhold;Rtcs(B), KBA	",
    "Hæmoglobintype gruppe;Hb(B) HÆMOGLOBINOPATIER, KBA	",
    "	",
    "IGF-bindende protein 3;P, KBA	",
    "Ig-Gen-rearrangement;B, KBA	",
    "IgH sekventering og mutationsanalyse;B, KBA	",
    "Imipramin;P, KBA	",
    "Immunglobulin A; P, KBA	",
    "Immunglobulin D;P, KBA	",
    "Immunglobulin E (specifik); P-, KBA	",
    "Immunglobulin E;P, KBA	",
    "Immunglobulin G subklasse gruppe;P, KBA	",
    "Immunglobulin G/Albumin; (Csv/P), KBA	",
    "Immunglobulin G; Csv, KBA	",
    "Immunglobulin G;P, KBA	",
    "Immunglobulin M;P, KBA	",
    "Immunglobulin -oligokloni;Csv, KBA	",
    "Indsendelse af HbA1c - patientinformation, PTI	",
    "Infliximab;P, KBA	",
    "Infliximab-Ab;P, KBA	",
    "Influenza, KMD	",
    "Information / Nyheder, 2	",
    "Inhalations + fødemid.panel - IgE;P Børn (<5 år), KBA	",
    "Inhalations+fødemid.panel-IgE;P + Torsk (f3)-IgE;P + Sojabønne (f14)-IgE;P Børn (<5 år) + GI-symptomer, KBA	",
    "Inhalationspanel-IgE;P Astma-Konjunktivitis-Rhinitis, KBA	",
    "Inhibin B;P, KBA	",
    "Insulin; P(fPt) og Insulin; P, KBA	",
    "Insulin-Ab;P, KBA	",
    "Insulinlignende vækstfaktor I;P, KBA	",
    "Interferon beta Ab(neutralis.);P, KBA	",
    "Interferon gamma(TB stim);T-lymc(B), KBA	",
    "Interleukin 2-receptor;P, KBA	",
    "Interleukin-28 (IL28B);DNA(spec.), KBA	",
    "Intrathekal antistofsyntese rettet mod Herpes Simplex virus (HSV) og Varicella Zoster virus (VZV). Antistof index (spinalvæske i forhold til serum), KMD",
    "Intravenøse katetre, dyrkning, KMD	",
    "Intrinsic faktor-Ab;P, KBA	",
    "	",
    "JAK2-gen [Exon]12;DNA, KBA	",
    "JAK2-gen[V617F];DNA, KBA	",
    "Japansk Encefalitis virus antistof (IgG, IgM) (SSI 2039), KBA	",
    "Jern; P, KBA	",
    "Kalium;P, KBA	",
    "Kalium;Pt(U)/U, KBA	",
    "Kapel og indlevering af afdøde - Patologi, SP	",
    "Karbamid;Dialysev (perit), KBA	",
    "Karbamid;P, KBA	",
    "Karbamid;Pt(U), KBA	",
    "Karnitin;P, KBA	",
    "Karyotypebestemmelse, KBA	",
    "Katekolaminer gruppe;Pt(U), KBA	",
    "Keratin-Ab(IgG);P (SSI 476), KBA	",
    "Kighoste (Bordetella pertussis og Bordetella parapertussis) ved PCR, KMD	",
    "Klinisk biokemi, 5	",
    "Klinisk immunologi, 5	",
    "Klinisk mikrobiologi, 5	",
    "Klorid;P, KBA	",
    "Knee Trimmings, KIA	",
    "Knoglemarvsundersøgelse +/- flowcytometrisk undersøgelse - Patologi, PAT	",
    "Koag. overflade-induceret [APTT];P, KBA	",
    "Koag. overflade-induceret [APTT];P (Roskilde), KBA	",
    "Koagulationsfaktor II (Koag)-Ab;P, KBA	",
    "Koagulationsfaktor II (koag.);P, KBA	",
    "Koagulationsfaktor II+VII+X [INR];P, KBA	",
    "Koagulationsfaktor II+VII+X;P, KBA	",
    "Koagulationsfaktor IX (Koag.);P, KBA	",
    "Koagulationsfaktor V-Ab (koag.);P, KBA	",
    "Koagulationsfaktor VII (koag.);P, KBA	",
    "Koagulationsfaktor VIII (enz.);P, KBA	",
    "Koagulationsfaktor VIII (koag.);P, KBA	",
    "Koagulationsfaktor X (koag.);P, KBA	",
    "Koagulationsfaktor X (koag.);P, KBA	",
    "Koagulationsfaktor X-Ab (koag.);P, KBA	",
    "Koagulationsfaktor XI (koag.);P, KBA	",
    "Koagulationsfaktor XII (koag.);P, KBA	",
    "Koagulationsfaktor XIII (enz.);P, KBA	",
    "Kobber;P, KBA	",
    "Kobber;Pt(U), KBA	",
    "Kolesterol HDL;P, KBA	",
    "Kolesterol LDL;P, KBA	",
    "Kolesterol;P, KBA	",
    "Kolinesterase;P, KBA	",
    "Kolinesterasetype gruppe;ChE(P), KBA	",
    "Kontakt til afdelingerne, 1	",
    "Kontroltiter gravid, KIA	",
    "Kortikotropin;P, KBA	",
    "Kortisol (LCMS);P, KBA	",
    "Kortisol frit;Pt(U), KBA	",
    "Kortisol;P, KBA	",
    "Kreatinin; P, KBA	",
    "Kreatinin; Pt(U)/U, KBA	",
    "Kreatinin;Dialysev (perit), KBA	",
    "Kreatinin-clearance; Nyre, KBA	",
    "Kreatinkinase MB; P, KBA	",
    "Kreatinkinase;P, KBA	",
    "Krom;P, KBA	",
    "Kromogranin A;P, KBA	",
    "Kromosom Y-gener (Yq11);DNA, KBA	",
    "Kryoglobulin; P, KBA	",
    "Kryopræcipitat, enkel komponent, KIA	",
    "Kryopræcipitat, pool, frosset, KIA	",
    "Kryopræcipitat, pool, tøet, KIA	",
    "Kuldeagglutinin (KAT), KIA	",
    "Kvalitetskontrol (Webquality), 2	",
    "Kviksølv;B, KBA	",
    "Kønscelledonor ej partner, KIA	",
    "Kønscelledonor til partner, KIA	",
    "	",
    "Lacosamid;P, KBA	",
    "Laktat;Csv, KBA	",
    "Laktat;P, KBA	",
    "Laktatdehydrogenase gruppe;LDH(P), KBA	",
    "Laktatdehydrogenase LD, KBA	",
    "Laktose belastning gruppe;Pt, KBA	",
    "Laktose intolerance-MCM6 (gentest), KBA	",
    "Laktosebelastning - patientinformation, PTI	",
    "Lamotrigin;P, KBA	",
    "Legionella pneumophila PCR, KMD	",
    "Legionella Urin Test - LUT, KMD	",
    "Leptospira arter-antistof (Weil);P (SSI 343), KBA	",
    "Leukocytantistof (Lymfocytotoksisk), KIA	",
    "Leukocytter;Asc, KBA	",
    "Leukocytter;B, KBA	",
    "Leukocytter;Csv, KBA	",
    "Leukocytter;Ledv, KBA	",
    "Leukocytter;Plv, KBA	",
    "Leukocyttype; antalk.(liste);B, KBA	",
    "Leukæmiklassifikation;B, Marv, Csv og Plv, KBA	",
    "Levetiracetam;P, KBA	",
    "Link til Transfusionsinstruktion - Regional, KIA	",
    "Lipoprotein (a);P, KBA	",
    "Liste over ISO 15189 akkrediterede analyser, 5	",
    "Lithium;P, KBA	",
    "Luftvejsvirus DNA/RNA, KMD	",
    "Lukkedage for blodprøvetagning, 4	",
    "Lupus antikoagulans;P, KBA	",
    "Lutropin (LH);P, KBA	",
    "Lymphocyttype gruppe;B, KIA	",
    "Lysosomale enzymer (gr 1);P, KBA	",
    "	",
    "Magnesium;P, KBA	",
    "Magnesium;U, KBA	",
    "Major centromere B-Ab(IgG);P, KBA	",
    "Malaria, KMD	",
    "Malaria - Prøvetagningsvejledning, KMD	",
    "Mangan;B, KBA	",
    "Mannanbindende lectin;P, KBA	",
    "Mannosebindende lektin - genotype, KIA, KIA	",
    "Mannosebindende lektin;P, KIA, KIA	",
    "MCH, KBA	",
    "MCHC, KBA	",
    "MCV, KBA	",
    "MEFV-gen;DNA, KBA	",
    "Meningokok-antistoffer (MAT);P (SSI 344), KBA	",
    "Metabolisk screening;U, KBA	",
    "Methadon + EDDP;U, KBA	",
    "Methotrexat; P, KBA	",
    "Methoxy-catecholaminer gruppe;P, KBA	",
    "Methylmalonat;P, KBA	",
    "Methæmoglobin;HB(B), KBA	",
    "Mexiletin;P, KBA	",
    "Midazolam;P, KBA	",
    "Mirtazapin;P, KBA	",
    "Mitokondrie-Ab(IgG);P (SSI 422), KBA	",
    "M-komponent(0 1);P, KBA	",
    "M-komponent;U, KBA	",
    "Mobiliseringspakke, KIA	",
    "Molekylærbiologisk undersøgelse Klinisk Patologi Næstved - Slagelse	",
    "Mononucleose-reaktion;P, KBA	",
    "Morbillivirus-antistof;P (SSI 255), KBA	",
    "Morphin;U+analog, KBA	",
    "MRSA, KMD	",
    "Mumps-Ab(IgG og IgM);P (SSI 260), KBA	",
    "Mumps-Ab;P immuntest (SSI 261), KBA	",
    "Muskel-specifik tyrosinkinase receptor-antistof;P, KBA	",
    "Myastenia gravis; pakke (SSI 487), KBA	",
    "Mycobacterium tuberculosis: Påvisning af Interferon-γ, KMD	",
    "Mycophenolat; P, KBA	",
    "Mycoplasma pneumoniae antistoffer, KMD	",
    "Mycoplasma pneumoniae PCR, KMD	",
    "Myoglobin;P, KBA	",
    "	",
    "NAT (HIV,HBV,HCV), KIA	",
    "Natrium; Pt(U)/U, KBA	",
    "Natrium;P, KBA	",
    "Nedbrud af OPUS/BCC, KMD	",
    "Neuron-specifik enolase (SSI 539); KBA, KBA	",
    "Nikkel;P, KBA	",
    "Nitrazepam;P, KBA	",
    "Noradrenalin;Pt(U), KBA	",
    "Noradrenalin;U, KBA	",
    "Norovirus, KMD	",
    "Nortriptylin;P, KBA	",
    "Nødblanket Sygehus, STS	",
    "Nødblanket til sygehuse, 3	",
    "Nødblanketter til praksis, 2	",
    "Nødblanketter til Praksis KBA, STP	",
    "Nødblanketter til Webreq Mikrobiologi, KMD	",
    "	",
    "O2 sat;Hb, KBA	",
    "Obduktioner - Patologi, PAT	",
    "Olanzapin;P, KBA	",
    "Opbevaring af patient oplysninger og væv samt biobank - Patologi, SP	",
    "Opsamling af afføring til undersøgelse for blod - patientinformation, PTI	",
    "Opsamling af døgnurin - patientinformation, PTI	",
    "Orexin-A [Hypocretin-1];Csv, KBA	",
    "Orosomucoid;P, KBA	",
    "Osmolalitet;P, KBA	",
    "Osmolalitet;U, KBA	",
    "Osteocalcin;P, KBA	",
    "Oversigt over analysedage for antistof undersøgelser, KMD	",
    "Oversigt over Laboratorie medicinsk vejledning - Patologi, SP	",
    "Oxalat;Pt(U), KBA	",
    "Oxcarbazepin;P, KBA	",
    "Oxyhæmoglobin;Hb, KBA	",
    "	",
    "Pancreas ø-celle(ICA)-Ab;P (SSI 461), KBA	",
    "PAPP A;P (doubletest), KBA	",
    "Paracetamol;P, KBA	",
    "Parasitter i Fæces, KMD	",
    "Parathyrin (PTH);P, KBA	",
    "Parietalcelle-Ab(IgG);P (SSI 467), KBA	",
    "Paroxetin;P, KBA	",
    "Parvovirus B19 - Lussingsyge, KMD	",
    "Parvovirus B-19-Ab gruppe;P, KBA	",
    "Patientvejledninger, 1	",
    "Patientvejledninger, 4	",
    "Patientvejledninger - Voksne.	",
    "Patologi, 5	",
    "pCO2;P, KBA	",
    "Penicillin G-antistof(IgE); P-, KBA	",
    "Penicillin V-antistof(IgE); P-, KBA	",
    "Peptidyldipeptidase A (ACE);P, KBA	",
    "Perampanel;P, KBA	",
    "Perifert blod til Patologi, KBA	",
    "Perphenazin;P, KBA	",
    "pH;P, KBA	",
    "Phenobarbital;P, KBA	",
    "Phenytoin frit;P, KBA	",
    "Phenytoin;P, KBA	",
    "Phytanat+Fede syrer gruppe;P, KBA	",
    "PLA2R-Ab(IgG);P, KBA	",
    "Plasma fra aferese, frosset, KIA	",
    "Plasma fra aferese, tøet, KIA	",
    "Plasma frosset, KIA	",
    "Plasma, tøet, KIA	",
    "Pneumokok urin test - PUT, KMD	",
    "pO2;P, KBA	",
    "Podninger, KMD	",
    "Poliovirus-Ab;P (SSI 232), KBA	",
    "Polymyositis/dermatomyositis, pakke; (SSI 499), KBA	",
    "Polyomavirus BK: PCR (kvant), KBA	",
    "Porfyrintype gruppe, KBA	",
    "Porphobilinogen;Pt(U), KBA	",
    "Posaconazol;P, KBA	",
    "Praksisrekvireringsliste, 2	",
    "Praksisrekvireringsliste, april 2017, PRL	",
    "Pregabalin;P, KBA	",
    "Primidon;P, KBA	",
    "Prisoversigt Klinisk Immunologisk Afdeling, KIA	",
    "Pro-brain natriuretisk pept.[BNP];P, KBA	",
    "Procalcitonin;P, KBA	",
    "PROC-gen;DNA, KBA	",
    "Progesteron;P, KBA	",
    "Proinsulin C-peptid; P(fPt), KBA	",
    "Proinsulin;P, KBA	",
    "Prokollagen I, N-term.propeptid;P, KBA	",
    "Prokollagen III, N-term.propeptid;P, KBA	",
    "Prolaktin;P, KBA	",
    "Propafenon;P, KBA	",
    "PROS1-gen;DNA, KBA	",
    "Prostataspecifikt antigen (ratio);P, KBA	",
    "Prostataspecifikt antigen;P, KBA	",
    "Protein C (enz.);P, KBA	",
    "Protein S frit;P, KBA	",
    "Protein/Kreatinin-ratio;U, KBA	",
    "Protein; Ledv, KBA	",
    "Protein; Pt(U), KBA	",
    "Protein;Asc, KBA	",
    "Protein;Csv, KBA	",
    "Protein;P, KBA	",
    "Protein;Plv, KBA	",
    "Prøvetagning i eget hjem/plejehjem, 2	",
    "Punkturvæske, KMD	",
    "Pus og Podninger, KMD	",
    "Pyridoxal 5-fosfat;P, KBA	",
    "Pyruvat;B(vB), KBA	",
    "Pyruvatkinase/Hb;B, KBA	",
    "	",
    "Quetiapin; stofk.;P, KBA	",
    "	",
    "Reagenser, prøvebeholdere, stregkoder mv. til patologius., STP	",
    "Reaktiv artrit efter tarminfektion. Kombinationsanalyse (SSI 318), KBA	",
    "Referenceintervaller for gravide, SKB	",
    "Rekvirering af patologiundersøgelse i WEBREQ, SP	",
    "Rekvirering af patologiundersøgelser i OPUS, SP	",
    "Rekvirering af patologius. på pt., som ikke er oprettet i et forløb i OPUS (fx rtg. afd.), SP	",
    "Rekvirering af patologius. på resektater med tyk- og endetarmskræft, SP	",
    "Rekvirering af patologius. på tarmpolypper der indgår i screeningsprogram, SP	",
    "Rekvisitioner til Patologi: Obduktioner samt histologi, cytologi og knoglemarv ved nødprocedure, SP	",
    "Renin;P, KBA	",
    "Reticulocytter; B-, KBA	",
    "Retinolbindende protein;P, KBA	",
    "Retsgenetisk undersøgelse ved faderskabssager, KBA	",
    "RhD - profylakse undersøgelse (mhp Rh-profylakse), KIA	",
    "RHD-gen;DNA - Antenatal genotypning, KIA	",
    "RhD-neg gravid opfølgning, KIA	",
    "Rhein;U, KBA	",
    "Rheumafaktor (IgA);P, KBA	",
    "Rheumafaktor;P, KBA	",
    "Ribavirin;P, KBA	",
    "Ringegrænser, 1	",
    "Ringegrænser, RG	",
    "Risperidon+9-hydroxy-Risperidon; stofk.;P, KBA	",
    "Rivaroxaban;P, KBA	",
    "Roskilde og Køge: Prøvetagning i eget hjem, STP	",
    "Roskilde og Køge: Vejledning til bestilling af utensilier, STP	",
    "Rotavirus, KMD	",
    "RS-virus (Respiratorisk syncytial virus), KMD	",
    "Rubella IgG antistoffer, KMD	",
    "Rubellavirus-antistof (IgG) ;P, KBA	",
    "Rufinamid;P, KBA	",
    "	",
    "Saccharomyces cerevisiae-Ab;P (SSI 486), KBA	",
    "Salicylat; P, KBA	",
    "Salmonella-Ab;P (SSI 361), KBA	",
    "Sarcolemma-Ab(IgG);P (SSI 472), KBA	",
    "Screening for lægemidler diverse;U, KBA	",
    "Screening for Rusmidler, KBA	",
    "Screening for Rusmidler - Bestilling af, KBA	",
    "Sedimentationsreaktion;B, KBA	",
    "Sektionsmateriale - Dyrkning, KMD	",
    "Selen;P, KBA	",
    "Serotonin gruppe;dU, KBA	",
    "Serotonin;P, KBA	",
    "SERPINA1-gen;DNA, KBA	",
    "SERPINC1-gen;DNA, KBA	",
    "Sertindol;P, KBA	",
    "Sertralin;P, KBA	",
    "Sexualhormonbindende globulin;P, KBA	",
    "Sirolimus;B, KBA	",
    "Sjögren syndrom (SSB)-Ab(IgG); P, KBA	",
    "Sjögren syndrom(SSA) Ab(IgG); P-, KBA	",
    "Smith's-Ab(IgG);P, KBA	",
    "Somatotropin [GH];, KBA	",
    "Specialvejl. / Biokemi, 1	",
    "Specialvejl. / Patologi, 1	",
    "Spermatozoa - vasectomi;sem, KBA	",
    "Spinalvæske - Dyrkning, KMD	",
    "Spinalvæske - Enterovirus PCR, KMD	",
    "Spinalvæske - Herpesvirus PCR (Herpes Simplex Virus 1+2 og Varizella Zoster Virus), KMD	",
    "SSI liste - prøver der kan sendes direkte til Statens Seruminstitut, KMD	",
    "Standard Test Syfilis (fuld us.);P (SSI 322), KBA	",
    "Standard Test Syfilis (screen);P (SSI 320), KBA	",
    "STAT3 mutationsanalyse, KBA	",
    "Steroid-metabolit gruppe;Pt(U), KBA	",
    "Stikskade, 1. undersøgelse, KIA	",
    "Stikskade, 2. undersøgelse, KIA	",
    "Stikskade, indekspatient, KIA	",
    "Stiripentol;P, KBA	",
    "Streptokok antistof 23-valent;P (SSI 695), KBA	",
    "Streptokok antistoffer (AST ASDB);P (SSI 355), KBA	",
    "Svampe, KMD	",
    "Svarmodtagere, tlf.svar og samtykke Patologi, SP	",
    "Svaroversigt i OPUS - Patologi, SP	",
    "Svartider Patologi, SP	",
    "Svedtest gruppe;Hudoverf, KBA	",
    "Svælgpodning, KMD	",
    "Sædkvalitet gruppe, KBA	",
    "Sædkvalitet undersøgelse (fertilitetstest) - patientinformation, PTI	",
    "Sædundersøgelse efter sterilisation (vasektomikontrol) - patientinformation, PTI	",
    "	",
    "Tacrolimus;B, KBA	",
    "Tarmpatogene bakterier (omfatter ikke Clostridium difficile), KMD	",
    "Tarmpatogene virus: Norovirus og Rotavirus i fæces, KMD	",
    "TCR-Gen-rearrangement;B, KBA	",
    "Tendon Achilles Bone block, KIA	",
    "Testosteron frit;P, KBA	",
    "Testosteron;P, KBA	",
    "Theophyllin;P, KBA	",
    "Thioguanin/Hæmoglobin,stofratio;B, KBA	",
    "Thiopurin Methyltransferase ery-TPMT fænotype, KBA	",
    "Thiopurin Methyltransferase Genotype TPMT, KBA	",
    "Thyreoglobulin-Ab;P, KBA	",
    "Thyreoidea Diagnostik, KBA	",
    "Thyreoidea Kontrol, KBA	",
    "Thyroglobulin;P, KBA	",
    "Thyroid-peroxidase-antistof; P, KBA	",
    "Thyrotropin (TSH); P, KBA	",
    "Thyrotropinreceptor-Ab;P, KBA	",
    "Thyroxin frit (T4);P, KBA	",
    "Thyroxinbindende globulin;P, KBA	",
    "Thyroxinbindingskap. [T4-uptake];P, KBA	",
    "Tick borne encephalitis virus (PCR) (SSI 679), KBA	",
    "Tick-borne-encephalitisvirus-antistof (IgG & IgM);P (SSI 227), KBA	",
    "Tidsbestilling, 4	",
    "Titin-IgG;P, KBA	",
    "T-Lymphocytter(helper);B, KIA	",
    "Tobramycin;P, KBA	",
    "Topiramat;P, KBA	",
    "Toxoplasma Gondii Antistoffer (IgG og IgM);P, KBA	",
    "Toxoplasmose, KMD	",
    "Transferrin(Fe-bindingssteder; P)—Jern; P-, KBA	",
    "Transfusionsinstruktion, KIA	",
    "Transfusionsinstruktion - FLOWOVERSIGT, KIA	",
    "Transfusionsinstruktion - HemoSafe automatkøleskab, udlevering og tilbagelevering af erytrocytkomponenter, KIA	",
    "Transfusionsinstruktion, Regional - Elektronisk blodbestilling via OPUS, KIA	",
    "Transfusionsinstruktion, Regional - Elektronisk opsætningskontrol og rapportering via OPUS, KIA	",
    "Transfusionsinstruktion, Regional - Elektronisk rapportering af blod & væv via OPUS, KIA	",
    "Transfusionsinstruktion, Regional - Indikation for transfusion med blodkomponenter, KIA	",
    "Transfusionsinstruktion, Regional - Komponentbehandling ved blødning, KIA	",
    "Transfusionsinstruktion, Regional. Afhentning af blod på vital indikation, KIA	",
    "Transfusionsinstruktion, Regional. Beskrivelse af blodkomponenter, -derivater og hæmostase-pharmaka, KIA	",
    "Transfusionsinstruktion, Regional. Bivirkninger og komplikationer, KIA	",
    "Transfusionsinstruktion, Regional. Blodbankens organisation, aktiviteter, tilladelser. Transfusionsråd, KIA	",
    "Transfusionsinstruktion, Regional. Blodkomponentbehandling ved særlige kliniske problemstillinger, KIA	",
    "Transfusionsinstruktion, Regional. Blodprøvetagning og bestilling til Klinisk Immunologisk Afdeling, KIA	",
    "Transfusionsinstruktion, Regional. Blodtypeserologiske analyser udført af blodbanken, KIA	",
    "Transfusionsinstruktion, Regional. Erytrocytkomponent (SAG-M) - Bestilling, afhentning, opsætning og kontrol, KIA	",
    "Transfusionsinstruktion, Regional. Forsendelse af blod med patienter, KIA	",
    "Transfusionsinstruktion, Regional. Laboratorier i Region Sjælland - Svartider - Informationsfolder, KIA	",
    "Transfusionsinstruktion, Regional. Livstruende blødning, herunder traumer med kraftig blødning, KIA	",
    "Transfusionsinstruktion, Regional. Plasmakomponent - Bestilling, afhentning, opsætning og kontrol, KIA	",
    "Transfusionsinstruktion, Regional. Quick guider, KIA	",
    "Transfusionsinstruktion, Regional. Transfusion af børn, KIA	",
    "Transfusionsinstruktion, Regional. Transfusionsbehandling - Overordnede ansvarsforhold, KIA	",
    "Transfusionsinstruktion, Regional. Transfusionsskema, Transfusionsjournal, KIA	",
    "Transfusionsinstruktion, Regional. Trombocytkomponent - Bestilling, afhentning, opsætning og kontrol, KIA	",
    "Transfusionsinstruktion, Regional. WEB-opslag i blodbanksystemet (InterInfo), KIA	",
    "Transfusionskomplikation, KIA	",
    "Treponema Pallidum flagellum-antistof, KIA	",
    "Triacylglycerollipase;P, KBA	",
    "Trichomonas Vaginalis, KMD	",
    "Triglycerider; P, KBA	",
    "Triiodthyronin(frit)P, KBA	",
    "Triple test gruppe;Foster, KBA	",
    "Trombocytaggregometri multistandard 1, KIA	",
    "Trombocytaggregometri multistandard 2, KIA	",
    "Trombocytantistofundersøgelse, KIA	",
    "Trombocytkomponent fra aferese, KIA	",
    "Trombocytkomponent fra aferese, bestrålet, KIA	",
    "Trombocytpool, KIA	",
    "Trombocytpool, bestrålet, KIA	",
    "Trombocytter; B, KBA	",
    "Trombocyttypebestemmelse, HPA-1a, KIA	",
    "Tromboelastometri (ROTEM), KIA	",
    "Trombofiliudredning, KBA	",
    "Troponin I; P, KBA	",
    "Troponin T; P, KBA	",
    "Tryptase;P, KBA	",
    "Tværstribet muskel-Ab(IgG);P, KBA	",
    "Tysabri-bindende antistoffer (Natalizumab), KBA	",
    "	",
    "U1 snRNP(70kDa+A+C)-Ab(IgG); P-, KBA	",
    "Urat; Ledv(spec.), KBA	",
    "Urat; P-, KBA	",
    "Urat; U og Pt(U), KBA	",
    "Urin Monovette opsamlingsglas - Prøver fra sygehuse, KMD	",
    "Urin Monovette opsamlingsglas (Borsyreurin) - Prøver fra almen praksis og prøver taget i hjemmet, KMD	",
    "Urindyrkninger, KMD	",
    "Urinundersøgelser stix;U, KBA	",
    "	",
    "Vaginalpodning, KMD	",
    "Valproat; P, KBA	",
    "Vancomycin;P, KBA	",
    "Vandprøver fra endoskoper, KMD	",
    "Vanillymandelat [VMA], KBA	",
    "Vanillymandelat [VMA]/Kreatinin;U, KBA	",
    "Varebestilling, 2	",
    "Variation på analyseresultater, KBA	",
    "Varicella Zoster Virus PCR (Herpes Simplex Virus type 1+2 og Varicella Zoster Virus), KMD	",
    "Varicella Zostervirus IgG antistof, KMD	",
    "Vasoaktivt intestinalt polypeptid;P, KBA	",
    "Vejledning til initial antibiotisk behandling af hyppigt forekommende infektioner hos voksne - lommekort, KMD	",
    "Venlafaxin; P, KBA	",
    "Vir prøve, KIA	",
    "Viskositet;P, KBA	",
    "Vitamin A;P, KBA	",
    "Vitamin B1;B, KBA	",
    "Vitamin B12;P, KBA	",
    "Vitamin C;P, KBA	",
    "Vitamin E;P, KBA	",
    "Von Willebrand antigen (imm.);P, KBA	",
    "Von Willebrand-faktor,aktiv(imm.);P, KBA	",
    "Voriconazol (SSI 607); P, KBA	",
    "VRE – undersøgelse for bærertilstand, KMD	",
    "Vævsdonor - allogen, KIA	",
    "Vævsprøver, KMD	",
    "Vævstypebestemmelse (HLA typebestemmelse), KIA	",
    "	",
    "Yersinia enterocolitica-Ab;P (SSI 365), KBA	",
    "	",
    "	",
    "	",
    "	",
    "Zika virus (RNA), KBA	",
    "	",
    "Zikavirus-Ab gruppe;P, KBA	",
    "Zink;P, KBA	",
    "Ziprasidon;P, KBA	",
    "Zonisamid;P, KBA	",
    "Zuclopentixol;P, KBA	",
    "	",
    "Øjenpodning, KMD	",
    "Ørepodning, KMD	",
    "Østradiol;P, KBA	",
    "	",
    "0 - Maximal tilladelig blodprøvevolumen på børn, SKB	",
    "	",
    "00 Akkrediterede analyser i Holbæk - Kalundborg - Odsherred	",
    "00 Akkrediterede analyser i Nykøbing F., Næstved og Slagelse	",
    "00 Akkrediterede analyser i Roskilde	",
    "	",
    "1 - Nyt prøvetagningssæt til mikrobiologiske prøver til Slagelse Sygehus, KMD	",
    "1 - SSI liste - prøver der kan sendes direkte til Statens Seruminstitut, KMD	",
    "1 - Vejledning i rekvirering (elektronisk) af bloddyrkninger, som tages af afdelingen selv (IKKE via BCC), KMD	",
    "1 - Vejledning i rekvirering af mikrobiologiske prøver via BCC-systemet, KMD	",
    "1,25-Dihydroxy-Vitamin D3 (Calcitriol);P, KBA	",
    "17-Hydroxyprogesteron;P, KBA	",
    "1-Generelle oplysninger, KMD	",
    "1-Utensilier til Klinisk Mikrobiologisk Afdeling, KMD	",
    "	",
    "25-OH-Vitamin D (D2 + D3), KBA	",
    "25-OH-Vitamin D3, KBA	",
    "	",
    "3- Methoxyadrenalin frit;P, KBA	",
    "3,4 Methylendioxyamfetamin;U, KBA	",
    "3-Methoxynoradrenalin frit;P, KBA	",
    "	",
    "5-Aminolevulinat;Pt(U), KBA	",
    "5-Hydroxyindolylacetat;Pt(U), KBA	",
    "	",
    "6-Methylthiopurinmetabolit/Hæmoglobin; stofratio;B, KBA	",
    "",]

module.exports = lab
